version: '3.9'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
      - db
    networks:
      - innoscripta
    volumes:
      - ./front:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - innoscripta
    volumes:
      - ./backend:/var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: innoscripta
      POSTGRES_PASSWORD: innoscripta
      POSTGRES_DB: innoscripta
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - innoscripta

  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - innoscripta

networks:
  innoscripta:
    driver: bridge
