version: '3.9'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
      - db
    networks:
      - innoscripta

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - innoscripta

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: innoscripta
      POSTGRES_PASSWORD: innoscripta
      POSTGRES_DB: innoscripta
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - innoscripta

  redis:
    image: redis:latest
    networks:
      - innoscripta

networks:
  innoscripta:
    driver: bridge
